// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAV0iKF9sCsswZ3-ZlrSwWYhGNVzbRUAKM',
    appId: '1:698580605510:web:5fecf792b947e93df3c847',
    messagingSenderId: '698580605510',
    projectId: 'hello-first-firebase',
    authDomain: 'hello-first-firebase.firebaseapp.com',
    storageBucket: 'hello-first-firebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_PjPYI0_OZ_ck80UfV6XCnX5ZNf_UHB0',
    appId: '1:698580605510:android:a4717f373eb70ba9f3c847',
    messagingSenderId: '698580605510',
    projectId: 'hello-first-firebase',
    storageBucket: 'hello-first-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzBxwsUv3KjIzBb4E_WDi5WCaz9-9bfDE',
    appId: '1:698580605510:ios:90a2ca0ddd0087d2f3c847',
    messagingSenderId: '698580605510',
    projectId: 'hello-first-firebase',
    storageBucket: 'hello-first-firebase.appspot.com',
    iosClientId: '698580605510-g1oastm71u66vv8n6u99ibd928no2rqf.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzBxwsUv3KjIzBb4E_WDi5WCaz9-9bfDE',
    appId: '1:698580605510:ios:90a2ca0ddd0087d2f3c847',
    messagingSenderId: '698580605510',
    projectId: 'hello-first-firebase',
    storageBucket: 'hello-first-firebase.appspot.com',
    iosClientId: '698580605510-g1oastm71u66vv8n6u99ibd928no2rqf.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAuth',
  );
}
